# Generated by Django 5.2.5 on 2025-08-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('lote', 'Lote'), ('oficina', 'Oficina')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('publicada', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
