# Generated by Django 5.2.5 on 2025-09-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_agente_propiedad_agente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='perfil',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
