# Generated by Django 5.2.5 on 2025-09-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_agente_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='foto_propiedad',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
