# Generated by Django 5.2.5 on 2025-09-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_propiedad_foto_propiedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='foto_propiedad',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/'),
        ),
    ]
