# Generated by Django 5.2.5 on 2025-09-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0006_alter_propiedad_foto_propiedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='perfil',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/'),
        ),
    ]
