# Generated by Django 5.2.5 on 2025-09-17 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0007_alter_agente_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='propiedades.agente'),
        ),
    ]
