# Generated by Django 5.2.5 on 2025-10-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0008_alter_propiedad_agente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='perfil',
            field=models.ImageField(blank=True, null=True, upload_to='agentes/'),
        ),
    ]
